// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tazo.DataAccess.Data;

#nullable disable

namespace Tazo.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250429075204_UpdatedMigration")]
    partial class UpdatedMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tazo.Models.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseCode")
                        .HasColumnType("text");

                    b.Property<string>("CourseTitle")
                        .HasColumnType("text");

                    b.Property<int>("NQF")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            CourseCode = "BCA1",
                            CourseTitle = "Bachelor of Computer and Information Science 1",
                            NQF = 7,
                            Year = 1
                        },
                        new
                        {
                            CourseId = 2,
                            CourseCode = "BCA2",
                            CourseTitle = "Bachelor of Computer and Information Science 2",
                            NQF = 7,
                            Year = 2
                        },
                        new
                        {
                            CourseId = 3,
                            CourseCode = "BCA3",
                            CourseTitle = "Bachelor of Computer and Information Science 3",
                            NQF = 7,
                            Year = 3
                        },
                        new
                        {
                            CourseId = 4,
                            CourseCode = "PDDA",
                            CourseTitle = "Postgraduate Diploma in Data Analytics",
                            NQF = 8,
                            Year = 1
                        });
                });

            modelBuilder.Entity("Tazo.Models.Entities.Module", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ModuleId"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<string>("ModuleCode")
                        .HasColumnType("text");

                    b.Property<string>("ModuleTitle")
                        .HasColumnType("text");

                    b.HasKey("ModuleId");

                    b.HasIndex("CourseId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("Tazo.Models.Entities.Module", b =>
                {
                    b.HasOne("Tazo.Models.Entities.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Tazo.Models.Entities.Course", b =>
                {
                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
